version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_PGSQL

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=globalface
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp


  app:
    build:
      context: .

    ports:
      - "8000:8000"
